# Generated by Django 4.0.4 on 2022-05-16 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('svd', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_user', models.CharField(max_length=200)),
                ('assigned_user', models.CharField(max_length=200)),
                ('assigned_svd', models.CharField(max_length=200)),
                ('ticket_number', models.IntegerField(default=81, unique=True)),
                ('state', models.CharField(default='Open', max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('device_type', models.CharField(max_length=200)),
                ('state', models.CharField(default='In warehouse', max_length=30)),
                ('purchase_date', models.DateTimeField(verbose_name='date purchased')),
                ('warranty', models.DateTimeField(verbose_name='warranty end')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.users')),
            ],
        ),
    ]
