# Generated by Django 4.0.4 on 2022-05-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0002_alter_tickets_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ticket_number',
            field=models.IntegerField(default=67, unique=True),
        ),
    ]
