# Generated by Django 4.0.4 on 2022-05-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0003_alter_tickets_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='node_id',
            field=models.CharField(default='None', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticket_number',
            field=models.IntegerField(default=91, unique=True),
        ),
    ]
