# Generated by Django 4.0.4 on 2022-05-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0004_devices_node_id_alter_tickets_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ticket_number',
            field=models.IntegerField(default=9, unique=True),
        ),
    ]
