# Generated by Django 4.0.4 on 2022-06-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0005_alter_tickets_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ticket_number',
            field=models.IntegerField(unique=True),
        ),
    ]
