# Generated by Django 4.0.4 on 2022-06-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0006_alter_tickets_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='description',
            field=models.CharField(max_length=100000),
        ),
    ]
