# Generated by Django 4.0.4 on 2022-06-01 10:54

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0007_alter_tickets_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ticket_number',
            field=models.IntegerField(default=builtins.id, unique=True),
        ),
    ]
