# Generated by Django 4.0.4 on 2022-06-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0009_remove_tickets_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='state',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
