# Generated by Django 4.0.4 on 2022-06-13 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0010_alter_tickets_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='affected_user',
            field=models.CharField(choices=[('USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.users'))], max_length=200),
        ),
    ]
