# Generated by Django 4.0.4 on 2022-06-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0011_alter_tickets_affected_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='affected_user',
            field=models.CharField(choices=[('USERS', None)], max_length=200),
        ),
    ]
