# Generated by Django 4.0.4 on 2022-06-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0012_alter_tickets_affected_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='device_type',
            field=models.CharField(choices=[('Virtual', 'Virtual'), ('Desktop', 'Desktop'), ('Laptop', 'Laptop')], max_length=200),
        ),
        migrations.AlterField(
            model_name='devices',
            name='state',
            field=models.CharField(choices=[('In warehouse', 'Warehouse'), ('Under repair', 'Repair'), ('Decomissioned', 'Decomissioned'), ('In use', 'In use')], default='In warehouse', max_length=30),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='affected_user',
            field=models.CharField(max_length=200),
        ),
    ]
