# Generated by Django 4.0.4 on 2022-06-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0014_tickets_affected_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
