# Generated by Django 4.0.4 on 2022-06-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0015_alter_users_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='node_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
