# Generated by Django 4.0.4 on 2022-07-02 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0018_alter_users_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='active',
        ),
        migrations.AlterField(
            model_name='devices',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 13, 13, 18, 752533), verbose_name='date purchased'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='warranty',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 1, 13, 13, 18, 752543), verbose_name='warranty end'),
        ),
    ]
