# Generated by Django 4.0.4 on 2022-07-02 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0019_remove_users_active_alter_devices_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='opening_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 13, 24, 18, 85354), verbose_name='opening date'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 13, 24, 18, 85161), verbose_name='date purchased'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='warranty',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 1, 13, 24, 18, 85174), verbose_name='warranty end'),
        ),
    ]
