# Generated by Django 4.0.4 on 2022-07-12 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0021_knowledgearticles_alter_devices_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='devices',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 12, 31, 2, 706371), verbose_name='date purchased'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='warranty',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 12, 31, 2, 706381), verbose_name='warranty end'),
        ),
        migrations.AlterField(
            model_name='knowledgearticles',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 12, 31, 2, 706717), verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='opening_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 12, 31, 2, 706575), verbose_name='opening date'),
        ),
    ]
