# Generated by Django 4.0.4 on 2022-07-29 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0022_users_state_alter_devices_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='priority',
            field=models.CharField(default='Low', max_length=50),
        ),
        migrations.AlterField(
            model_name='devices',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 10, 8, 4, 321762), verbose_name='date purchased'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='warranty',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 28, 10, 8, 4, 321773), verbose_name='warranty end'),
        ),
        migrations.AlterField(
            model_name='knowledgearticles',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 10, 8, 4, 322114), verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='opening_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 10, 8, 4, 321960), verbose_name='opening date'),
        ),
    ]
