# Generated by Django 4.0.4 on 2022-08-02 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0024_alter_devices_purchase_date_alter_devices_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 12, 5, 56, 836277), verbose_name='date purchased'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='state',
            field=models.CharField(choices=[('In warehouse', 'Warehouse'), ('Under repair', 'Repair'), ('Decommissioned', 'Decommissioned'), ('In use', 'In use')], default='In warehouse', max_length=30),
        ),
        migrations.AlterField(
            model_name='devices',
            name='warranty',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 1, 12, 5, 56, 836287), verbose_name='warranty end'),
        ),
        migrations.AlterField(
            model_name='knowledgearticles',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 12, 5, 56, 836606), verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='opening_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 12, 5, 56, 836465), verbose_name='opening date'),
        ),
    ]
