# Generated by Django 4.1 on 2022-08-10 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0027_tickets_history_alter_devices_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 12, 3, 13, 349007), verbose_name='date purchased'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='warranty',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 9, 12, 3, 13, 349016), verbose_name='warranty end'),
        ),
        migrations.AlterField(
            model_name='knowledgearticles',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 12, 3, 13, 349362), verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='opening_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 12, 3, 13, 349179), verbose_name='opening date'),
        ),
    ]
