# Generated by Django 4.1 on 2022-08-10 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0028_alter_devices_purchase_date_alter_devices_warranty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 12, 27, 50, 993396), verbose_name='date purchased'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='warranty',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 9, 12, 27, 50, 993405), verbose_name='warranty end'),
        ),
        migrations.AlterField(
            model_name='knowledgearticles',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 12, 27, 50, 993716), verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='history',
            field=models.CharField(blank=True, default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='opening_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 12, 27, 50, 993575), verbose_name='opening date'),
        ),
    ]
